export const packagesData = [
  {
    id: 1,
    name: "Exotic Island Getaway",
    duration: "7 days",
    price: "$1999",
    status: "active",
  },
  {
    id: 2,
    name: "Cultural Europe Tour",
    duration: "10 days",
    price: "$2499",
    status: "inactive",
  },
  {
    id: 3,
    name: "Adventure Safari Expedition",
    duration: "14 days",
    price: "$2999",
    status: "active",
  },
  {
    id: 4,
    name: "Romantic Paris Getaway",
    duration: "5 days",
    price: "$1799",
    status: "inactive",
  },
  {
    id: 5,
    name: "Mystical Asian Discovery",
    duration: "12 days",
    price: "$2799",
    status: "active",
  },
  {
    id: 6,
    name: "Tropical Paradise Escape",
    duration: "8 days",
    price: "$2199",
    status: "inactive",
  },
  {
    id: 7,
    name: "Historic Landmarks Tour",
    duration: "9 days",
    price: "$2399",
    status: "active",
  },
  {
    id: 8,
    name: "Wildlife Safari Adventure",
    duration: "11 days",
    price: "$2699",
    status: "inactive",
  },
  {
    id: 9,
    name: "Enchanting European Journey",
    duration: "14 days",
    price: "$2999",
    status: "active",
  },
  {
    id: 10,
    name: "Cruise to Exotic Destinations",
    duration: "7 days",
    price: "$1999",
    status: "inactive",
  },
  {
    id: 11,
    name: "Majestic Mountain Expedition",
    duration: "10 days",
    price: "$2499",
    status: "active",
  },
  {
    id: 12,
    name: "Cultural Immersion in Asia",
    duration: "12 days",
    price: "$2799",
    status: "inactive",
  },
  {
    id: 13,
    name: "Luxury Mediterranean Cruise",
    duration: "9 days",
    price: "$2399",
    status: "active",
  },
  {
    id: 14,
    name: "Serenity Spa Retreat",
    duration: "5 days",
    price: "$1799",
    status: "inactive",
  },
  {
    id: 15,
    name: "Adventure in the Amazon Rainforest",
    duration: "14 days",
    price: "$2999",
    status: "active",
  },
  {
    id: 16,
    name: "City Lights and Nightlife Tour",
    duration: "6 days",
    price: "$1899",
    status: "inactive",
  },
  {
    id: 17,
    name: "Discovering Ancient Civilizations",
    duration: "11 days",
    price: "$2699",
    status: "active",
  },
  {
    id: 18,
    name: "Coastal Beach Bliss",
    duration: "7 days",
    price: "$1999",
    status: "inactive",
  },
  {
    id: 19,
    name: "Enchanted Castle Escapade",
    duration: "8 days",
    price: "$2199",
    status: "active",
  },
  {
    id: 20,
    name: "African Safari Adventure",
    duration: "15 days",
    price: "$3199",
    status: "inactive",
  },
];
